var db = {
    interesses: [
        {
            "id": 1,
            "descricao": "Analista de TI 1 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        
        },
        {
            "id": 2,
            "descricao": "Analista de TI 2 - DB APOIO INTEGRAL.",
            "empresa" : "ADESCOLA" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 3,
            "descricao": "Analista de TI 3 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 4,
            "descricao": "Analista de TI 4 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 5,
            "descricao": "Analista de TI 5 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 6,
            "descricao": "Analista de TI 6 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 7,
            "descricao": "Analista de TI 7 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 8,
            "descricao": "Analista de TI 8 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 9,
            "descricao": "Analista de TI 9 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        },
        {
            "id": 10,
            "descricao": "Analista de TI 10 - DB APOIO INTEGRAL.",
            "empresa" : "wabtec" ,
            'sobreaempresa' :"With more than 27,000 employees in over 50 countries around the world, Wabtec provides innovative solutions to our freight rail, passenger transit and industrial customers. Our history of innovation dates back a century and a half to George Westinghouse's invention of the air brake.",
            'sobreavaga' :"Empresa localizada na cidade de contagem/ mg do ramo administrativo contrata analista de ti Requisitos: • desejável ensino superior completo em tecnologia da informação ou áreas afins.",
            "tempo": "Integral",
            "cargo" : "Analista de sistemas",
            "competenciadavaga" : "CSS;Desenvolvimento de back-end;ERP;Go;HTML;JQuery;JavaScript:Lógica;PHP",
            "salario": "3500,00",
            "email": "wabtec@wabtec.email.com",
            "telefone": "31-322-736-8031",
            "website": "http://wabtec.com"
        }
    ]
}